// Copyright (c) 2022 Contributors to the Suwayomi project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import 'package:flutter/material.dart';

import 'app_constants.dart';
import 'enum.dart';

enum DBKeys {
  serverUrl('http://127.0.0.1:4567'),
  sourceLanguageFilter(["all", "lastUsed", "en", "localsourcelang"]),
  extensionLanguageFilter(["installed", "update", "en", "all"]),
  sourceLastUsed(null),
  themeMode(ThemeMode.system),
  basicCredentials(null),
  readerMode(ReaderMode.webtoon),
  readerPageLayout(ReaderPageLayout.automatic),
  readerPageLayoutSkipFirstPage(false),
  readerPadding(0.0),
  readerPaddingLandscape(0.0),
  readerMagnifierSize(1.0),
  readerNavigationLayout(ReaderNavigationLayout.disabled),
  invertTap(false),
  showTapZones(true),
  enableFileLog(false),
  useSystemProxy(true),
  showPlus(null),
  repoUrl(null),
  installLocalCount(0),
  downloadedBadge(false),
  unreadBadge(true),
  languageBadge(false),
  l10n(null),
  mangaFilterDownloaded(null),
  mangaFilterUnread(null),
  mangaFilterCompleted(null),
  chapterFilterDownloaded(null),
  chapterFilterUnread(null),
  chapterFilterBookmarked(null),
  mangaSort(MangaSort.alphabetical),
  mangaSortDirection(true), // asc=true, dsc=false
  chapterSort(ChapterSort.source),
  chapterSortDirection(false), // asc=true, dsc=false
  libraryDisplayMode(DisplayMode.grid),
  sourceDisplayMode(DisplayMode.grid),
  gridMangaCoverWidth(192.0),
  purchaseDone(false),
  purchaseExpireMs(0),
  purchaseToken(null),
  serverApiUrl('https://api.tachimanga.app'),
  autoBackup(true),
  markNeedAskRate(false),
  initLocation(null),
  scrollAnimation(false),
  doubleTapZoomIn(true),
  pinchToZoom(true),
  longPressActionMenu(true),
  classicStartButton(false),
  pinSourceIdList(<String>[]),
  onlySearchPinSource(false),
  disableBypass(false),
  watermarkSwitch(true),
  themeKey('default'),
  themeBlendLevel(10.0),
  themePureBlackDarkMode(false),
  autoBackupFrequency(FrequencyEnum.off),
  autoBackupLimit(2),
  showStatusBar(false),
  defaultTab(DefaultTabEnum.auto),
  swipeRightToGoBackMode(SwipeRightToGoBackMode.always),
  migrateChapterFlag(true),
  migrateCategoryFlag(true),
  migrateTrackFlag(true),
  removeDownloadsIfMigrate(true),
  // Deprecated
  categoryIdsToUpdate(<String>[]),
  // Deprecated
  alwaysAskCategoryToUpdate(true),
  defaultCategory(kCategoryAlwaysAskValue),
  lockType(LockTypeEnum.off),
  lockInterval(LockIntervalEnum.always),
  lockPasscode(''),
  secureScreen(SecureScreenEnum.off),
  incognitoMode(false),
  incognitoModeUsed(false),
  dateFormat(DateFormatEnum.yMMMd),
  libraryShowMangaCount(false),
  showDirectFlag(false),
  bgEnable(false),
  downloadTaskInParallel(1),
  deleteDownloadAfterRead(0),
  deleteDownloadAfterReadTodoList(<String>[]),
  appIconKey('default'),
  backupToCloud(false),
  autoRefreshTitle(false),
  receiveTimeout(null),
  autoScrollInterval(2000),
  autoSmoothScrollInterval(4000),
  readTimeShowLogo(true),
  keepScreenOnWhileReading(false),
  applePencilDoubleTapAction(ApplePencilActon.previousPage),
  applePencilSqueezeAction(ApplePencilActon.nextPage),
  readerUsePhotoView(true),
  forceEnableScroll(false),
  userAgentType(UserAgentTypeEnum.defaultWebView),
  mouseWheelSpeed(1.0),
  ;

  const DBKeys(this.initial);

  final dynamic initial;
}
